config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[index edit update] do
    get :profile
  end
  resources :organizations, only: %i[show new create index]
  # resources :organizations, only: [:index]

  devise_for :users, controllers: { registrations: "registrations" }

  resources :offers do
    resources :applications, only: %i[new create]
  end

  resources :applications, only: %i[show destroy update]

  get 'dashboard', to: 'pages#dashboard'
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://content.magnumphotos.com/wp-content/uploads/2016/05/cortex/nyc94317-photographer-featured.jpg);">
  <div class="container">
    <h1>Find your volunteer <br> job in Berlin.</h1>
  </div>
</div>

app/views/shared/_card_organization.html.erb
      <div class="card-group">
        <div class="card h-100 card-style" style="width: 18rem;">
          <%= link_to organization_path(organization) do %>
          <div class="card-body-organizations">
            <div class="d-flex align-items-center flex-column">
              <img src="<%= organization.logo_url %>" class="card-organization-logo avatar-bordered pt-4" />
              <p class="card-district pb-2 pt-4"><strong><%= organization.name %></strong></p>
            </div>
          </div>
        <% end %>
        </div>
      </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Made by A, M, J, T <i class="fa-solid fa-person-digging"></i>
  </div>
</div>

app/views/shared/_modal_app.html.erb
<div class="modal fade" id="modal-<%= applicant %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><%= application.title %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        <%= application.message %>
      </div>
      <div class="modal-footer">
        <% if application.status.nil? && current_user.organization %>
          <div >
            <%= simple_form_for application do |f| %>
              <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
              <%= f.submit 'Accept', class: 'btn btn-primary' %>
            <% end %>
          </div>
          <div>
            <%= simple_form_for application do |f| %>
              <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
              <%= f.submit 'Reject', class: 'btn btn-secondary' %>
            <% end %>
          </div>
        <% elsif application.status.nil? %>
          <p class='application-tag'>pending</p>
        <% else %>
          <p class='application-tag'><%= application.status %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div>
  <nav class="navbar navbar-dark navbar-expand-lg navbar-container">
    <div class="d-flex justify-content-between navbar_links_container container">
      <div class="d-flex align-items-center">
        <%= link_to "WOLLENTIER", root_path, class: "navbar-brand" %>
        <%= link_to "Jobs", offers_path, method: :get, class: "main-nav-link nav-spacing" %>
        <% if current_user && current_user.organization? %>
          <%= link_to "Volunteers", users_path, method: :get, class: "main-nav-link" %>
        <% else %>
          <%= link_to "Organizations", organizations_path, method: :get, class: "main-nav-link" %>
        <% end %>
      </div>
        <%# <form class="d-flex" role="links"> %>
            <ul class="navbar-nav d-flex align-items-center">
                <% if user_signed_in? %>
                  <li class="nav item dropdown" style="position: initial !important;">
                    <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= current_user.profile_url %>">
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><%= link_to "Profile", edit_user_registration_path, method: :get, class: "dropdown-item" %></li>
                      <li><%= link_to "Dashboard", dashboard_path, method: :get, class: "dropdown-item" %></li>
                      <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
                    </ul>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "Sign Up", new_user_registration_path, class: "nav-btn-primary" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Login", new_user_session_path, class: "main-nav-link" %>
                  </li>
                <% end %>
            </ul>
        </form>
    </div>
  </nav>
</div>

app/views/shared/_navbar_divs_changed.html.erb
<div>
  <nav class="navbar navbar-dark navbar-expand-lg">
    <div class="d-flex justify-content-between navbar_links_container">

      <div class="d-flex align-items-center>
        <%= link_to "WOLLENTIER", root_path, class: "navbar-brand" %>
        <%= link_to "Jobs", offers_path, method: :get, class: "nav-link nav-spacing" %>
        <%= link_to "Organizations", organizations_path, method: :get, class: "nav-link" %>
      </div>

      <div>
        <ul class="navbar-nav d-flex align-items-center">

            <% if user_signed_in? %>
              <li class="nav item dropdown">
                <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2960&q=80" />
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><%= link_to "Profile", edit_user_registration_path, method: :get, class: "dropdown-item" %></li>
                  <li><%= link_to "Dashboard", dashboard_path, method: :get, class: "dropdown-item" %></li>
                  <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
                </ul>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-btn-primary" %>
              </li>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
        </ul>
      </div>

    </div>
  </nav>
</div>

app/views/shared/_user_form.html.erb
<%= simple_form_for(user) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email%>
  <%= f.input :phone_number%>
  <%= f.input :interests%>
  <%= f.input :role%>
  <%= f.submit %>
<% end %>