config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[index edit update] do
    get :profile
  end
  resources :organizations, only: %i[show new create index]
  # resources :organizations, only: [:index]

  devise_for :users, controllers: { registrations: "registrations" }

  resources :offers do
    resources :applications, only: %i[new create]
  end

  resources :applications, only: %i[show destroy update]

  get 'dashboard', to: 'pages#dashboard'
end

app/views/pages/_ngo_dashboard.html.erb
<div class="banner-dashboard" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://t3.ftcdn.net/jpg/02/68/81/22/360_F_268812279_cVMsQJ8UWfV8k8HO2oqjhRY1XhopgE68.jpg);">
  <div class="container">
    <h1><%= current_user.organization.name %></h1>
  </div>
</div>

<div data-controller="dashboard">
  <div class="sub-nav">
    <ul class="d-flex flex-row justify-content-start container align-items-center" data-action="click->dashboard#display">
      <li class="nav-link mt-3 me-5" ><p>Open jobs</p></li>
      <li class="nav-link mt-3 me-5"><p>Applications</p></li>
      <li class="nav-link mt-3"><p>Volunteers</p></li>
    </ul>
  </div>

  <div class="dash-content container mb-5">
    <div class="open-jobs-container" data-dashboard-target="openjobs">
      <div class="d-flex justify-content-between pt-3">
        <h3>Open jobs</h3>
        <%= link_to "Add offer", new_offer_path, class:"btn btn-primary" %>
      </div>
      <div class="row row-cols-12 row-cols-md-4 g-4 pt-3">
        <% @offers.each do |offer| %>
          <%= render partial: 'offers/card_offer', locals: { offer: offer}  %>
        <% end %>
      </div>
    </div>



    <div class="applications-container" data-dashboard-target="applications">
      <h3 class="mt-4">Applications for my job offers</h3>
      <% @applications.each do |application| %>
        <div class="application-container d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center ms-3">
            <div class="avatar-large" style="background-image: url(<%= application.user.profile_url %>)">
            </div>
            <h5 class="card-title ms-4"><%= application.title %></h5>
          </div>
          <div class="d-flex align-items-center">
            <p class="application-time me-5"><%= (application.created_at).strftime("%A, %d %b %Y %l:%M %p") %></p>
            <div class="application-actions d-flex align-items-center">
            <p class="application-tag-user application-tag-<%= application.status.nil? ? "pending": application.status.downcase %>"><%= application.status.nil? ? "Pending": application.status.downcase  %></p>
            <button type="button" class="btn btn-secondary me-4" data-bs-toggle="modal" data-bs-target="#modal-<%= application.id %>">
              Details
            </button>
          </div>
          </div>
        </div>
      <%= render "shared/modal_app", application: application, applicant: application.id %>
      <% end %>
    </div>


    <div class="volunteers-container" data-dashboard-target="volunteers">
      <h3 class="mt-4 mb-2">Your volunteers</h3>
      <div class="row row-cols-12 row-cols-md-4 g-4 pt-3">
        <% @hired_volunteers.each do |application| %>
          <%= render partial: 'offers/volunteer_card', locals: { application: application}  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_volunteer_dashboard.html.erb
<div class="banner-dashboard" style="background-image: url(https://images.pexels.com/photos/7135057/pexels-photo-7135057.jpeg);">
  <div class="container">
    <h1><%= current_user.first_name%> <%= current_user.last_name%></h1>
  </div>
</div>

<div data-controller="dashboard-volunteer">
  <div class="sub-nav">
    <ul class="d-flex flex-row justify-content-start container align-items-center" data-action="click->dashboard-volunteer#display">
      <li class="nav-link mt-3 me-5"><p>Applications</p></li>
      <li class="nav-link mt-3"><p>Organizations</p></li>
    </ul>
  </div>

  <div class="dash-content container mb-5">

    <div class="applications-container" data-dashboard-volunteer-target="applications">
      <h3 class="mt-4">Applications for my job offers</h3>
      <% @applications.each do |application| %>
        <div class="application-container d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center ms-3">
            <div class="avatar-large" style="background-image: url(<%= application.user.profile_url %>)">
            </div>
            <h5 class="card-title ms-4"><%= application.title %></h5>
          </div>
          <div class="d-flex align-items-center">
            <p class="application-time me-5"><%= (application.created_at).strftime("%A, %d %b %Y %l:%M %p") %></p>
            <div class="application-actions d-flex align-items-center">
            <p class="application-tag-user application-tag-<%= application.status.nil? ? "pending": application.status.downcase %>"><%= application.status.nil? ? "Pending": application.status.downcase  %></p>
            <button type="button" class="btn btn-secondary me-4" data-bs-toggle="modal" data-bs-target="#modal-<%= application.id %>">
              Details
            </button>
          </div>
          </div>
        </div>
      <%= render "shared/modal_app", application: application, applicant: application.id %>
      <% end %>
    </div>

    <div class="volunteers-container" data-dashboard-volunteer-target="organizations">
      <h3 class="mt-4 mb-2">Your organizations</h3>
      <div class="row row-cols-12 row-cols-md-4 g-4 pt-3">
        <% @hired_organizations.each do |accepted_application| %>
          <%= render partial: 'shared/card_organization', locals: { organization: accepted_application.offer.organization}  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<% if current_user.volunteer? %>
  <%= render "volunteer_dashboard", :offers => @offers %>
<% else %>
  <%= render "ngo_dashboard", :applications => @applications %>
<% end %>

app/views/pages/home.html.erb
<div class="banner-home" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://rs.projects-abroad.ie/v1/products/product-5b55908a058a9.[1090].jpeg);">


<section id="main" class="hero d-flex align-items-center justify-content-center">
  <div class="container">
    <h1 class="mt-5">Find your volunteer <br> job in Berlin.</h1>
    <div>
      <div class="col-lg-6 d-flex flex-column" data-controller="filter" data-filter-offers-value="<%= @offers.to_json %>">
        <%# <h2 data-aos="fade-up">Connecting Wollentiers in Berlin</h2>
        <p data-aos="fade-up" data-aos-delay="100">We are here to connect dedicated people with jobs to help build a better world blablabla something super duper deep and meaningful about life in general and how great it is to help. </p> %>

        <%= form_with url: offers_path, method: :get, class: "d-flex align-items-stretch mb-3 mt-4" do %>

          <%= text_field_tag :query,
            params[:query],
            class: "form-control placeholder",
            placeholder: "Enter ZIP code or keyword"
          %>
          <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>

        <%# <h4 class="mt-5">Search by category</h4> %>
        <div class="d-flex justify-content-between mt-4">
          <div>
            <%= form_with url: offers_path, method: :get do %>
            <%= hidden_field_tag :query, "Kids" %>
              <button class="btn btn-category btn-circle btn-xl" id="Kids">
                  <i class="fa-solid fa-children fa-xl"></i>
                <br>

              </button>
              <p class="tags">Kids</p>
            <% end %>
          </div>

          <%= form_with url: offers_path, method: :get do %>
          <%= hidden_field_tag :query, "Seniors" %>
            <button class="btn btn-category btn-circle btn-xl" id="Seniors">
                <i class="fa-solid fa-person-cane fa-xl"></i>
              <br>

            </button>
            <p class="tags">Seniors</p>
          <% end %>

          <%= form_with url: offers_path, method: :get do %>
          <%= hidden_field_tag :query, "Refugees" %>
            <button class="btn btn-category btn-circle btn-xl" id="Refugees">
              <i class="fa-solid fa-handshake fa-xl"></i>
              <br>

            </button>
            <p class="tags">Refugees</p>
          <% end %>

          <%= form_with url: offers_path, method: :get do %>
          <%= hidden_field_tag :query, "Community" %>
            <button class="btn btn-category btn-circle btn-xl" id="Community">
              <i class="fa-solid fa-heart-pulse fa-xl"></i>
              <br>

            </button>
            <p class="tags">Community</p>
          <% end %>

          <%= form_with url: offers_path, method: :get do %>
          <%= hidden_field_tag "all" %>
            <button class="btn btn-category btn-circle btn-xl" id="all">
              <i class="fa-solid fa-rectangle-list fa-xl"></i>
              <br>
            </button>
            <p class="tags">All</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
</div>