config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[index edit update] do
    get :profile
  end
  resources :organizations, only: %i[show new create index]
  # resources :organizations, only: [:index]

  devise_for :users, controllers: { registrations: "registrations" }

  resources :offers do
    resources :applications, only: %i[new create]
  end

  resources :applications, only: %i[show destroy update]

  get 'dashboard', to: 'pages#dashboard'
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :organization
  has_many :applications, dependent: :destroy

  validates :title, presence: true
  validates :description, length: { minimum: 10 }
  validates :category, presence: true
  validates :location, presence: true
  validates :frequency, presence: true
  validates :contact_person, presence: true
  validates :district, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @offers = policy_scope(Offer).includes(:organization)
    if params[:query].present?
      sql_query = <<~SQL
        offers.title @@ :query
        OR offers.description @@ :query
        OR offers.category @@ :query
        OR offers.location @@ :query
        OR organizations.name @@ :query
        OR organizations.description @@ :query
      SQL
      @offers = @offers.where(category: params[:query])
    end
    @offers = Offer.all.includes(:organization) if @offers.empty?
  end

  def show
    @application = Application.new
    @offers = Offer.where(category: @offer.category).where.not(id: @offer.id).limit(4)
    authorize @offer
    @markers = [{
      lat: @offer.latitude,
      lng: @offer.longitude
    }]
    # authorize @application
    @related_offers = Offer.where(category: @offer.category).where.not(id: @offer.id).limit(4).group_by(&:category)
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.organization = current_user.organization
    authorize @offer
    if @offer.save
      redirect_to offers_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @offer
  end

  def update
    authorize @offer
    if @offer.update(offer_params)
      redirect_to offers_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @offer
    @offer.destroy
    redirect_to offers_path, status: :see_other
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :category, :location, :start_date, :frequency,
                                  :contact_person, :district)
  end

  def set_offer
    @offer = Offer.find(params[:id])
  end
end

app/views/offers/_card_offer.html.erb
<div class="card-group">
  <div class="card h-100 card-style" style="width: 18rem;">
    <%= link_to offer_path(offer) do %>
      <div class="card-body">
        <div class="card-badge card-badge-<%= offer.category.downcase %>">
          <span><%= offer.category %></span>
        </div>
        <p class="card-district district-style"><%= offer.district %></p>
        <p class="card-title"><strong><%= offer.title %></strong></p>
        <p class="card-frequency district-style"><%= offer.frequency %></p>
        <img src="<%= offer.organization.logo_url %>" class="card-offer-logo avatar-bordered" />
      </div>
    <% end %>
  </div>
</div>

app/views/offers/_form.html.erb
<%= simple_form_for offer do |f| %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :category %>
    <%= f.input :location %>
    <%= f.input :district %>
    <%= f.input :start_date %>
    <%= f.input :frequency %>
    <%= f.input :contact_person %>
    <%= f.input :photo, as: :file%>
  </div>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/offers/_volunteer_card.html.erb
<div class="card-group mb-4 pb-4">
  <div class="card h-100 card-style " style="width: 18rem;">
      <div class="card-body-volunteer">
        <div class="d-flex flex-column align-items-center">
          <div class="avatar-xlarge" style="background-image: url(<%= application.user.profile_url %>)"></div>
          <p class="card-title mt-4"><strong><%= application.user.first_name %></strong> <%= application.user.last_name %></p>
          <div class="contact d-flex justify-content-between">
            <div>
              <p class="district-style">Phone</p>
              <p class="district-style"  style="margin-top: -10px">E-Mail</p>
            </div>
            <div>
              <p class="card-district contact-details"><%= application.user.phone_number %></p>
              <p class="card-district contact-details"  style="margin-top: -10px"><%= application.user.email %></p>
            </div>
          </div>
      </div>
  </div>
</div>
</div>

app/views/offers/_volunteer_card_index.html.erb
<div class="card-group pb-2">
  <div class="card h-100 card-style " style="width: 18rem;">
      <div class="card-body-volunteer">
        <div class="d-flex flex-column align-items-center">
          <div class="avatar-xlarge" style="background-image: url(<%= user.profile_url %>)"></div>
          <p class="card-title mt-4"><strong><%= user.first_name %></strong> <%= user.last_name %></p>
          <div class="contact d-flex justify-content-between">
            <div>
              <p class="district-style">Phone</p>
              <p class="district-style"  style="margin-top: -10px">E-Mail</p>
              <p class="district-style"  style="margin-top: -10px">Interests</p>
            </div>
            <div>
              <p class="card-district contact-details"><%= user.phone_number %></p>
              <p class="card-district contact-details"  style="margin-top: -10px"><%= user.email %></p>
              <p class="card-district volunteer-interests-badge"  style="margin-top: -10px"><%= user.interests.first %></p>
            </div>
          </div>
      </div>
  </div>
</div>
</div>

app/views/offers/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6">
      <div class="containerd-flex justify-content-center">
          <h2>Edit your job offer</h2>
          <%= render "form", offer: @offer %>
      </div>
    </div>
    <div class="col-6">
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="sub-nav mb-4">
  <ul class="d-flex flex-row justify-content-start container align-items-center">
    <div>
      <%= form_with url: offers_path, method: :get do %>
      <%= hidden_field_tag :query, "Kids" %>
        <button class="btn nav-link mt-3 me-5" id="Kids"><p><i class="fa-solid fa-children fa-l pe-2"></i>Kids</p></button>
      <% end %>
    </div>
    <div>
      <%= form_with url: offers_path, method: :get do %>
      <%= hidden_field_tag :query, "Seniors" %>
        <button class="btn nav-link mt-3 me-5" id="Seniors"><p><i class="fa-solid fa-person-cane fa-l pe-2"></i>Seniors</p></button>
      <% end %>
    </div>
    <div>
      <%= form_with url: offers_path, method: :get do %>
      <%= hidden_field_tag :query, "Refugees" %>
        <button class="btn nav-link mt-3 me-5" id="Refugees"><p><i class="fa-solid fa-handshake fa-l pe-2"></i>Refugees</p></button>
      <% end %>
    </div>
    <div>
      <%= form_with url: offers_path, method: :get do %>
      <%= hidden_field_tag :query, "Community" %>
        <button class="btn nav-link mt-3 me-5" id="Community"><p><i class="fa-solid fa-heart-pulse fa-xl pe-2"></i></i>Community</p></button>
      <% end %>
    </div>
    <div>
      <%= form_with url: offers_path, method: :get do %>
      <%= hidden_field_tag "all" %>
        <button class="btn nav-link mt-3 me-5" id="all"><p><i class="fa-solid fa-rectangle-list fa-l pe-2"></i>All Jobs</p></button>
      <% end %>
    </div>
  </ul>
</div>

<div class="container">
  <div class="row row-cols-12 row-cols-md-4 g-4 mb-5">
    <% @offers.each do |offer| %>
      <%= render partial: 'card_offer', locals: { offer: offer}  %>
    <% end %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-6">
      <div class="containerd-flex justify-content-center">
          <h2>Create your job offer</h2>
          <%= render "form", offer: @offer %>
      </div>
    </div>
    <div class="col-6">
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class="banner position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://content.magnumphotos.com/wp-content/uploads/2016/05/cortex/nyc94317-photographer-featured.jpg);">
  <img class="position-absolute card-offer-logo-show-banner" src="<%= @offer.organization.logo_url %>" />
</div>
<div class="job-detail-container">
  <div class="container">
    <div class="row">
      <%# title and description %>
        <div class="col-8">
          <h1><%= @offer.title %></h1>
          <div class="card-badge card-badge-<%= @offer.category.downcase %>"><span><%= @offer.category %></span></div>
          <p class="job-description"><%= @offer.description %></p>
          <!-- Button trigger modal -->
          <% if user_signed_in? && current_user.volunteer? %>
          <button type="button" class="btn btn-primary-mdutra mt-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Apply for Job
          </button>
          <% end %>
          <div class="d-flex flex-row mb-3 justify-content-start">
            <!-- PUNDIT - PLEASE ADD THE BUTTONS BELOW TO THEIR RELATED DIV-->
            <% if policy(@offer).edit? %>
              <%= link_to "Edit this offer", edit_offer_path(@offer), class: "btn btn-primary-mdutra" %>
            <% end %>
            <%= button_to "Delete this offer", @offer, method: :delete, class: "btn btn-primary" if policy(@offer).destroy? %>
          </div>


        </div>
        <div class="col-4">
          <div class="d-flex flex-column mb-5">
            <div class="p-2 position-relative">
              <h3><strong><%= @offer.organization.name %></strong></h3>
              <p>District: <%= @offer.district %></p>
              <p>Phone Number: <%= @offer.organization.user.phone_number %></p>
              <p>Email: <%= @offer.organization.user.email %></p>
            </div>
            <div class="p-2">
              <div class="row gutters-sm" id="map"
                  style="width: 100%; height: 300px;"
                  data-controller="map"
                  data-map-markers-value="<%= @markers.to_json %>"
                  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
                  data-map-zoom-value=15>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Job application</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "applications/form", application: @application %>
      </div>
    </div>
  </div>
</div>

  <!-- further recommendations-->
  <section class="py-5">
    <div class="container">
      <h1 class="mx-2">Related Jobs</h1>
      <% @related_offers.each do |category, offers| %>
        <div class="row row-cols-12 row-cols-md-4 g-4">
          <% offers.each do |offer| %>
            <%= render partial: 'card_offer', locals: { offer: offer}  %>
          <% end %>
        </div>
      <% end %>
    </div>
  </section>